import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db/prisma";

export const dynamic = "force-dynamic";

// GET - Fetch draft prospects for public display
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const year = searchParams.get("year") || "2026";

    const prospects = await prisma.draftProspect.findMany({
      where: {
        draftYear: parseInt(year),
      },
      orderBy: { rank: "asc" },
    });

    if (prospects.length === 0) {
      // Return fallback data
      return NextResponse.json({
        success: true,
        prospects: getFallbackProspects(),
        year: parseInt(year),
        source: "fallback",
      });
    }

    return NextResponse.json({
      success: true,
      prospects,
      year: parseInt(year),
      source: "database",
    });
  } catch (error) {
    console.error("Error fetching draft prospects:", error);
    return NextResponse.json({
      success: true,
      prospects: getFallbackProspects(),
      year: 2026,
      source: "fallback",
    });
  }
}

// Verified 2026 NBA Draft prospects - sourced from ESPN Big Board & Mock Draft (Feb 2026)
// Stats reflect 2025-26 college season averages
function getFallbackProspects() {
  return [
    {
      id: "1",
      rank: 1,
      name: "Darryn Peterson",
      position: "PG/SG",
      school: "Kansas",
      height: "6'6\"",
      weight: 205,
      age: 19,
      ppg: 22.6,
      rpg: 4.7,
      apg: 2.1,
      fgPct: 49.4,
      threePct: 43.2,
      ftPct: 80.6,
      strengths: ["Elite scoring ability", "Three-point shooting", "Shot creation", "Size for position"],
      weaknesses: ["Hamstring injury concerns", "Assist numbers", "Defensive consistency"],
      comparison: "Devin Booker",
      projectedPick: "1-3",
      draftYear: 2026,
      espnId: "5041955",
    },
    {
      id: "2",
      rank: 2,
      name: "AJ Dybantsa",
      position: "SF",
      school: "BYU",
      height: "6'9\"",
      weight: 210,
      age: 19,
      ppg: 22.9,
      rpg: 7.1,
      apg: 3.9,
      fgPct: 53.0,
      threePct: 31.8,
      ftPct: 76.2,
      strengths: ["Complete offensive game", "Length and athleticism", "Versatility", "Finishing at the rim"],
      weaknesses: ["Three-point consistency", "Defensive consistency", "Shot selection"],
      comparison: "Jayson Tatum",
      projectedPick: "1-3",
      draftYear: 2026,
      espnId: "5142718",
    },
    {
      id: "3",
      rank: 3,
      name: "Cameron Boozer",
      position: "PF/C",
      school: "Duke",
      height: "6'9\"",
      weight: 250,
      age: 18,
      ppg: 22.9,
      rpg: 9.5,
      apg: 4.2,
      fgPct: 58.3,
      threePct: 37.5,
      ftPct: 75.8,
      strengths: ["Scoring inside and out", "Rebounding", "Passing for size", "65.3% true shooting"],
      weaknesses: ["Vertical lift concerns", "Rim protection", "Defensive positioning"],
      comparison: "Chris Bosh",
      projectedPick: "1-3",
      draftYear: 2026,
      espnId: "5041935",
    },
    {
      id: "4",
      rank: 4,
      name: "Caleb Wilson",
      position: "PF/C",
      school: "North Carolina",
      height: "6'10\"",
      weight: 215,
      age: 19,
      ppg: 19.5,
      rpg: 11.0,
      apg: 2.7,
      fgPct: 58.1,
      threePct: 25.0,
      ftPct: 70.4,
      strengths: ["Elite motor", "Physicality", "Rebounding", "Most popular name among scouts"],
      weaknesses: ["Three-point shooting", "Free throw shooting", "Perimeter game"],
      comparison: "Pascal Siakam",
      projectedPick: "3-6",
      draftYear: 2026,
      espnId: "5095151",
    },
    {
      id: "5",
      rank: 5,
      name: "Kingston Flemings",
      position: "PG",
      school: "Houston",
      height: "6'4\"",
      weight: 190,
      age: 19,
      ppg: 15.7,
      rpg: 3.3,
      apg: 5.1,
      fgPct: 60.6,
      threePct: 42.6,
      ftPct: 78.0,
      strengths: ["Elite field goal efficiency", "Court vision", "Three-point shooting", "Rapid rise to lottery"],
      weaknesses: ["Finishing over length", "Size for position", "Turnover management"],
      comparison: "Jrue Holiday",
      projectedPick: "4-8",
      draftYear: 2026,
      espnId: "5149077",
    },
    {
      id: "6",
      rank: 6,
      name: "Mikel Brown Jr.",
      position: "PG",
      school: "Louisville",
      height: "6'5\"",
      weight: 190,
      age: 20,
      ppg: 16.6,
      rpg: 3.0,
      apg: 5.1,
      fgPct: 37.4,
      threePct: 26.8,
      ftPct: 80.5,
      strengths: ["Dynamic ball-handling", "Size for position", "Playmaking vision", "Court generalship"],
      weaknesses: ["Shooting efficiency", "Streaky three-point shooting", "Consistency"],
      comparison: "Darius Garland",
      projectedPick: "5-10",
      draftYear: 2026,
      espnId: "5101761",
    },
    {
      id: "7",
      rank: 7,
      name: "Keaton Wagler",
      position: "SG",
      school: "Illinois",
      height: "6'6\"",
      weight: 185,
      age: 19,
      ppg: 17.9,
      rpg: 5.0,
      apg: 4.3,
      fgPct: 48.0,
      threePct: 44.4,
      ftPct: 80.7,
      strengths: ["Elite three-point shooting", "3-and-D potential", "46-point game at Purdue", "Basketball IQ"],
      weaknesses: ["Needs to add strength", "Defensive consistency", "Finishing through contact"],
      comparison: "Tyrese Haliburton",
      projectedPick: "5-12",
      draftYear: 2026,
      espnId: "5254165",
    },
    {
      id: "8",
      rank: 8,
      name: "Nate Ament",
      position: "SF/PF",
      school: "Tennessee",
      height: "6'10\"",
      weight: 207,
      age: 19,
      ppg: 14.9,
      rpg: 6.4,
      apg: 2.5,
      fgPct: 41.8,
      threePct: 31.1,
      ftPct: 76.5,
      strengths: ["Length and wingspan", "Scoring versatility", "Defensive potential", "Skill warrants patience"],
      weaknesses: ["Shooting efficiency", "Needs to add weight", "Playmaking development"],
      comparison: "Brandon Ingram",
      projectedPick: "6-12",
      draftYear: 2026,
      espnId: "5164559",
    },
    {
      id: "9",
      rank: 9,
      name: "Koa Peat",
      position: "PF/C",
      school: "Arizona",
      height: "6'8\"",
      weight: 235,
      age: 19,
      ppg: 14.8,
      rpg: 5.8,
      apg: 2.0,
      fgPct: 57.0,
      threePct: 35.3,
      ftPct: 60.8,
      strengths: ["Physical strength", "Finishing at rim", "Strong rebounder", "Body control"],
      weaknesses: ["Free throw shooting", "Limited perimeter game", "Offensive polish"],
      comparison: "Julius Randle",
      projectedPick: "8-15",
      draftYear: 2026,
      espnId: "5041953",
    },
    {
      id: "10",
      rank: 10,
      name: "Braylon Mullins",
      position: "SG",
      school: "UConn",
      height: "6'6\"",
      weight: 196,
      age: 20,
      ppg: 11.7,
      rpg: 3.7,
      apg: 1.5,
      fgPct: 47.3,
      threePct: 38.0,
      ftPct: 81.3,
      strengths: ["Outstanding shotmaker", "Basketball IQ", "Competitive fire", "Well-developed scoring sense"],
      weaknesses: ["Creating off dribble", "Playmaking", "Volume scoring"],
      comparison: "Desmond Bane",
      projectedPick: "8-15",
      draftYear: 2026,
      espnId: "5196916",
    },
    {
      id: "11",
      rank: 11,
      name: "Hannes Steinbach",
      position: "PF",
      school: "Washington",
      height: "6'11\"",
      weight: 220,
      age: 20,
      ppg: 17.8,
      rpg: 11.5,
      apg: 1.8,
      fgPct: 53.7,
      threePct: 35.1,
      ftPct: 76.6,
      strengths: ["Double-double machine", "Soft touch", "Program record for freshman double-doubles", "Rebounding dominance"],
      weaknesses: ["Lateral quickness", "Perimeter separation", "Foot speed in space"],
      comparison: "Lauri Markkanen",
      projectedPick: "10-16",
      draftYear: 2026,
      espnId: "5281370",
    },
    {
      id: "12",
      rank: 12,
      name: "Thomas Haugh",
      position: "SF/PF",
      school: "Florida",
      height: "6'9\"",
      weight: 215,
      age: 22,
      ppg: 17.2,
      rpg: 6.6,
      apg: 2.3,
      fgPct: 50.5,
      threePct: 38.0,
      ftPct: 77.0,
      strengths: ["Three-point shooting", "Basketball IQ", "Offensive versatility", "Toughness"],
      weaknesses: ["Age relative to class", "Athletic ceiling", "Defensive foot speed"],
      comparison: "Sam Hauser",
      projectedPick: "10-18",
      draftYear: 2026,
      espnId: "",
    },
    {
      id: "13",
      rank: 13,
      name: "Darius Acuff Jr.",
      position: "PG",
      school: "Arkansas",
      height: "6'3\"",
      weight: 190,
      age: 19,
      ppg: 19.9,
      rpg: 2.8,
      apg: 5.9,
      fgPct: 44.0,
      threePct: 36.5,
      ftPct: 82.0,
      strengths: ["Tough competitor", "Controls game pace", "Strong 8-2 start", "Passing vision"],
      weaknesses: ["Size for NBA", "Finishing over length", "Defensive impact"],
      comparison: "Tyrese Haliburton",
      projectedPick: "12-20",
      draftYear: 2026,
      espnId: "",
    },
    {
      id: "14",
      rank: 14,
      name: "Labaron Philon Jr.",
      position: "PG/SG",
      school: "Alabama",
      height: "6'4\"",
      weight: 175,
      age: 20,
      ppg: 21.3,
      rpg: 3.3,
      apg: 5.1,
      fgPct: 51.1,
      threePct: 38.5,
      ftPct: 75.4,
      strengths: ["Shot creation", "Explosive scoring", "SEC Player of the Week x3", "Off-dribble shooting"],
      weaknesses: ["Size and frame", "Defensive effort", "Turnover management"],
      comparison: "Trae Young",
      projectedPick: "12-20",
      draftYear: 2026,
      espnId: "4873090",
    },
    {
      id: "15",
      rank: 15,
      name: "Brayden Burries",
      position: "SG/PG",
      school: "Arizona",
      height: "6'4\"",
      weight: 205,
      age: 20,
      ppg: 14.5,
      rpg: 3.8,
      apg: 4.0,
      fgPct: 45.5,
      threePct: 37.0,
      ftPct: 79.5,
      strengths: ["Two-way play", "Physicality", "Fluid scorer", "Defensive versatility"],
      weaknesses: ["Shot creation", "Turnover-prone", "Consistency"],
      comparison: "Marcus Smart",
      projectedPick: "15-25",
      draftYear: 2026,
      espnId: "",
    },
  ];
}
