-- Enable Row-Level Security on ALL public tables
-- This blocks access via Supabase's public REST API (anon/authenticated roles)
-- while NOT affecting Prisma access (postgres superuser bypasses RLS)
--
-- Run this in Supabase SQL Editor: Dashboard > SQL Editor > New Query

-- ============================================================================
-- Prisma-managed tables
-- ============================================================================
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Player" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Game" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlayerStat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamStat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiInsight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Setting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiTracker" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SocialMediaPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Article" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdPlacement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DraftProspect" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HistoricalRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SeasonHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForumCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForumThread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForumPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PostReaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForumReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatRoom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContactMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Take" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Poll" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PollOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PollVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TakeReaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Repost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Bookmark" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Prediction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Challenge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChallengeVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StatCheck" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgingTake" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserBlock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TakeReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameNotificationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Prisma migration tracking table
-- ============================================================================
ALTER TABLE IF EXISTS "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
